kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: group{{ group_number }}
  name: group{{ group_number }}-role
rules:
- apiGroups: [""]
  resources: ["pods", "services", "deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
