apiVersion: v1
kind: ResourceQuota
metadata:
  name: group{{ group_number }}-quota
  namespace: group{{ group_number }}
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi
    persistentvolumeclaims: "4"
    requests.storage: 10Gi
