kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: group{{ group_number }}-binding
  namespace: group{{ group_number }}
subjects:
- kind: User
  name: group{{ group_number }}
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: group{{ group_number }}-role
  apiGroup: rbac.authorization.k8s.io
